# Generated by Django 4.1.3 on 2022-11-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отдел',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phoneNumber', models.PositiveIntegerField(verbose_name='Номер телефона')),
                ('adress', models.CharField(max_length=255, verbose_name='Адресс')),
                ('depatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departments', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудник',
            },
        ),
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('avto_nomer', models.CharField(max_length=255, verbose_name='Номер автомобиля')),
                ('vin', models.CharField(max_length=255, verbose_name='VIN код автомобиля')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Изготовитель')),
                ('date_purchase', models.DateField(verbose_name='Дата покупки')),
                ('year_manufacture', models.DateField(verbose_name='Год изготовления')),
                ('chassis', models.CharField(max_length=255, verbose_name='Шасси')),
                ('engine_power', models.PositiveIntegerField(verbose_name='Мощность двигателя')),
                ('tech_inspection', models.DateField(verbose_name='Техосмотр')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('type', models.CharField(choices=[('Грузовой', 'Грузовой'), ('Пассажирский', 'Пассажирский')], default='PASSENGER', max_length=20)),
                ('load', models.PositiveIntegerField(verbose_name='Макс. Загрузка пассажиров/груза')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
    ]
