# Generated by Django 4.1.3 on 2022-11-16 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phoneNumber', models.PositiveIntegerField(verbose_name='Номер телефона')),
                ('adress', models.CharField(max_length=255, verbose_name='Адресс')),
                ('nomer', models.CharField(max_length=255, verbose_name='Номер автомобиля')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудник',
            },
        ),
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('vin', models.CharField(max_length=255, verbose_name='VIN код автомобиля')),
                ('brand', models.CharField(max_length=255, verbose_name='ФИО')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Изготовитель')),
                ('date_purchase', models.DateField(verbose_name='Дата покупки')),
                ('year_manufacture', models.DateField(verbose_name='Год изготовления')),
                ('chassis', models.CharField(max_length=255, verbose_name='Шасси')),
                ('engine_power', models.PositiveIntegerField(verbose_name='Мощность двигателя')),
                ('tech_inspection', models.DateField(verbose_name='Техосмотр')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('nomer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee', verbose_name='номер автомобиля')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
    ]
