# Generated by Django 4.1.3 on 2022-11-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avto',
            name='nomer',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nomer',
        ),
        migrations.AddField(
            model_name='avto',
            name='avto_nomer',
            field=models.CharField(default=0, max_length=255, verbose_name='Номер автомобиля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avto',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='avto',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Марка'),
        ),
    ]
