# Generated by Django 4.1.3 on 2022-11-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_avto_nomer_remove_employee_nomer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avto',
            name='brand',
        ),
        migrations.AddField(
            model_name='avto',
            name='load',
            field=models.PositiveIntegerField(default=0, verbose_name='Макс. Загрузка пассажиров/груза'),
            preserve_default=False,
        ),
    ]
