# Generated by Django 4.1.9 on 2023-08-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_avto_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('avto_nomer', models.CharField(max_length=255, unique=True, verbose_name='Номер автомобиля')),
                ('vin', models.CharField(max_length=255, unique=True, verbose_name='VIN код автомобиля')),
                ('year_manufacture', models.DateField(verbose_name='Год изготовления')),
                ('chassis', models.CharField(blank=True, max_length=255, verbose_name='Шасси')),
                ('engine_power', models.PositiveIntegerField(verbose_name='Мощность двигателя')),
                ('tech_inspection', models.DateField(verbose_name='Техосмотр')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('average_fuel_use', models.PositiveSmallIntegerField(verbose_name='Среднее кол-во топлива на 100 км.')),
                ('type', models.CharField(choices=[('Грузовой', 'Грузовой'), ('Пассажирский', 'Пассажирский')], default='PASSENGER', max_length=20)),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='depatment',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='FIO',
        ),
        migrations.AddField(
            model_name='employee',
            name='firstName',
            field=models.CharField(default='neew', max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='lastName',
            field=models.CharField(default='neewLast', max_length=255, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='middleName',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
        migrations.DeleteModel(
            name='Avto',
        ),
        migrations.AddField(
            model_name='auto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee', verbose_name='Водитель'),
        ),
    ]
