# Generated by Django 4.1.3 on 2022-11-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_avto_brand_avto_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='avto',
            name='type',
            field=models.CharField(choices=[('FREIGHT', 'Грузовой'), ('PASSENGER', 'Пассажирский')], default='PASSENGER', max_length=20),
        ),
    ]
